version: '3'

x-common:
  &common
  build:
    context: .
    args:
      USER_ID: ${USER_ID:-1001}
      GROUP_ID: ${GROUP_ID:-1001}
  volumes:
    - .:/app
  depends_on:
    - db
  environment:
    - DATABASE_URL=postgresql://ocds_data_summary:devpassword@db/ocds_data_summary
    - DJANGO_DEBUG=True
    - NODE_ENV=development
    - DJANGO_DEBUG_TOOLBAR
    - DJANGO_SECRET_KEY=not-secret-in-dev
    - DJANGO_WHITENOISE_AUTOREFRESH=True
    - TAG_MANAGER_ENABLED=False

services:

  web:
    <<: *common
    ports:
      - "8000:8000"
    command: ./manage.py runserver 0.0.0.0:8000

  worker:
    <<: *common
    command: ./manage.py qcluster

  db:
    image: postgres:12
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=ocds_data_summary
      - POSTGRES_PASSWORD=devpassword
      - POSTGRES_DB=ocds_data_summary
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data:
