# Generated by Django 4.2.4 on 2023-08-22 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_category_options_alter_entity_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='summary',
            options={'ordering': ['-created'], 'verbose_name_plural': 'Summaries'},
        ),
    ]
