# Generated by Django 4.2.4 on 2023-08-22 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_summary_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='label',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='entity',
            name='label',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
